fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    git: 'puppetlabs-git'
    vcsrepo: 'puppetlabs-vcsrepo'
    epel: 'stahnma-epel'
    python:
      repo: 'stankevich-python'
      ref: '1.11.0'
    mysql: 'puppetlabs-mysql'
    uwsgi:
      repo: 'engage-uwsgi'
      ref: '1.2.0'
    selinux: 'camptocamp-selinux'
  symlinks:
    patchwork: "#{source_dir}"
