fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    git: 'puppetlabs-git'
    vcsrepo: 'puppetlabs-vcsrepo'
    epel: 'stahnma-epel'
    python: 
      repo: 'stankevich-python'
      ref: '1.9.4'
    mysql: 'puppetlabs-mysql'
  symlinks:
    patchwork: "#{source_dir}"
