fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    git: 'puppetlabs-git'
    vcsrepo: 'puppetlabs-vcsrepo'
    epel: 'stahnma-epel'
    python:
      repo: 'stankevich-python'
      ref: '1.9.4'
    mysql: 'puppetlabs-mysql'
    uwsgi:
      repo: 'cwood-uwsgi'
      ref: '0.2.2'
  symlinks:
    patchwork: "#{source_dir}"
