---
sudo: false
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake validate lint spec SPEC_OPTS='--format documentation'"

matrix:
  fast_finish: true
  include:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.8.0"
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 4.2.0"

notifications:
  email: false
