---
sudo: false
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake validate lint spec SPEC_OPTS='--format documentation'"

rvm:
  - 2.1.7

env:
  matrix:
    - PUPPET_VERSION="~> 3.1.0"
    - PUPPET_VERSION="~> 3.8.0"
    - PUPPET_VERSION="~> 4.3.0"

matrix:
  fast_finish: true

notifications:
  email: false
